---
#
# Ansible Playbook for building Instant Veins
# Copyright (C) 2018 Christoph Sommer <sommer@ccs-labs.org>
#
# Documentation for this template is at http://veins.car2x.org/
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#


- name: Install base packages
  apt:
    state: present
    name:
      - bison
      - flex
      - tcl-dev
      - tk-dev
      - openjdk-17-jre
      - qtbase5-dev
      - libopenscenegraph-dev
      - xvfb
      - libwebkit2gtk-4.0-dev
      - doxygen
      - graphviz
      - python3-numpy
      - python3-pandas
      - python3-matplotlib

- name: Install base python packages
  pip:
    name: posix-ipc==1.0.5

- name: Create default directories
  become_user: veins
  file:
    path: /home/veins/{{item}}
    state: directory
    owner: veins
    group: veins
    mode: 0755
  with_items:
    - src

- name: Download source
  get_url:
    url: "{{ omnetpp_tarball_url }}"
    dest: "/home/veins/src/{{ omnetpp_tarball_filename }}"
    checksum: "sha1:{{ omnetpp_tarball_sha1 }}"

- name: Unpack source
  become_user: veins
  shell: |
    set -exu
    tar -xvf "{{ omnetpp_tarball_filename }}"
  args:
    executable: /bin/sh
    chdir: /home/veins/src
    creates: "/home/veins/src/{{ omnetpp_dir }}"

- name: Create symlink
  become_user: veins
  file:
    src: "/home/veins/src/{{ omnetpp_dir }}"
    dest: /home/veins/src/omnetpp
    state: link

- name: Add to path - sh
  become_user: veins
  lineinfile:
    dest: /home/veins/.shrc
    line: 'PATH="$PATH:$HOME/src/omnetpp/bin"'

- name: Add to path - bash
  become_user: veins
  lineinfile:
    dest: /home/veins/.bashrc
    line: 'PATH="$PATH:$HOME/src/omnetpp/bin"'

- name: Disable osgearth
  become_user: veins
  shell: |
    source setenv
    set -exu
    source ~/.shrc
    perl -p -i -e 's/WITH_OSGEARTH=yes/WITH_OSGEARTH=no/' configure.user

  args:
    executable: /bin/bash
    chdir: /home/veins/src/omnetpp


#- name: Build OMNeT++
#  become_user: veins
#  shell: |
#    source setenv
#    set -exu
#    source ~/.shrc
#    perl -p -i -e 's/WITH_OSGEARTH=yes/WITH_OSGEARTH=no/' configure.user
#    xvfb-run ./configure
#    make -j2
#  args:
#    executable: /bin/bash
#    chdir: /home/veins/src/omnetpp
#    creates: /home/veins/src/omnetpp/bin/opp_run


