---
#
# Ansible Playbook for building Instant Veins
# Copyright (C) 2018 Christoph Sommer <sommer@ccs-labs.org>
#
# Documentation for this template is at http://veins.car2x.org/
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#


- name: Create default directories for user
  become_user: veins
  file:
    path: /home/veins/{{item}}
    state: directory
    owner: veins
    group: veins
    mode: 0755
  with_items:
    - .local/share/applications

- name: Install base packages
  apt:
    state: present
    name:
      - epiphany-browser

- name: Launcher Entry
  become_user: veins
  copy:
    content: |
      [Desktop Entry]
      Type=Application
      Name=OMNeT++ IDE
      Exec=omnetpp -data /home/veins/workspace.omnetpp -import /home/veins/src/veins/README.txt
      Icon=/home/veins/src/omnetpp/ide/icon.xpm
      Categories=Science;
      StartupWMClass=OMNeT++ IDE
    dest: /home/veins/.local/share/applications/omnetpp.desktop
    mode: 0755

- name: Launcher Entry
  become_user: veins
  copy:
    content: |
      [Desktop Entry]
      Type=Application
      Name=veins_launchd
      Exec=xterm -class veins_launchd -e /home/veins/src/veins/bin/veins_launchd -vv
      Icon=network-transmit-receive-symbolic
      Categories=Science;
      StartupWMClass=veins_launchd
    dest: /home/veins/.local/share/applications/veins_launchd.desktop
    mode: 0755

- name: Profile directory for online documentation
  file:
    path: /home/veins/.local/share/org.gnome.Epiphany.WebApp-veins-onlinedocs
    state: directory
    owner: veins
    group: veins
    mode: 0755

- name: Launcher file for online documentation
  become_user: veins
  copy:
    content: |
      [Desktop Entry]
      Type=Application
      Name=Veins documentation online
      Exec=epiphany --application-mode --profile='/home/veins/.local/share/org.gnome.Epiphany.WebApp-veins-onlinedocs' 'http://veins.car2x.org/documentation/'
      Icon=help-faq
      Categories=Science;
      StartupWMClass=org.gnome.Epiphany.WebApp-veins-onlinedocs
    dest: /home/veins/.local/share/org.gnome.Epiphany.WebApp-veins-onlinedocs/org.gnome.Epiphany.WebApp-veins-onlinedocs.desktop
    mode: 0755

- name: App file for online documentation
  become_user: veins
  copy:
    content: ""
    dest: /home/veins/.local/share/org.gnome.Epiphany.WebApp-veins-onlinedocs/.app
    mode: 0755

- name: Launcher entry for online documentation
  become_user: veins
  file:
    src: /home/veins/.local/share/org.gnome.Epiphany.WebApp-veins-onlinedocs/org.gnome.Epiphany.WebApp-veins-onlinedocs.desktop
    dest: /home/veins/.local/share/applications/org.gnome.Epiphany.WebApp-veins-onlinedocs.desktop
    state: link

- name: Profile directory for offline documentation
  file:
    path: /home/veins/.local/share/org.gnome.Epiphany.WebApp-veins-offlinedocs
    state: directory
    owner: veins
    group: veins
    mode: 0755

- name: Launcher file for offline documentation
  become_user: veins
  copy:
    content: |
      [Desktop Entry]
      Type=Application
      Name=Veins source code documentation (offline)
      Exec=epiphany --application-mode --profile='/home/veins/.local/share/org.gnome.Epiphany.WebApp-veins-offlinedocs' 'file:///home/veins/src/veins/doc/doxy/index.html'
      Icon=help-contents
      Categories=Science;
      StartupWMClass=org.gnome.Epiphany.WebApp-veins-offlinedocs
    dest: /home/veins/.local/share/org.gnome.Epiphany.WebApp-veins-offlinedocs/org.gnome.Epiphany.WebApp-veins-offlinedocs.desktop
    mode: 0755

- name: App file for offline documentation
  become_user: veins
  copy:
    content: ""
    dest: /home/veins/.local/share/org.gnome.Epiphany.WebApp-veins-offlinedocs/.app
    mode: 0755

- name: Launcher entry for offline documentation
  become_user: veins
  file:
    src: /home/veins/.local/share/org.gnome.Epiphany.WebApp-veins-offlinedocs/org.gnome.Epiphany.WebApp-veins-offlinedocs.desktop
    dest: /home/veins/.local/share/applications/org.gnome.Epiphany.WebApp-veins-offlinedocs.desktop
    state: link

- name: Favourites
  become_user: veins
  shell: |
    set -exu
    xvfb-run gsettings set org.gnome.shell favorite-apps "['omnetpp.desktop', 'veins_launchd.desktop', 'org.gnome.Epiphany.WebApp-veins-onlinedocs.desktop', 'org.gnome.Epiphany.WebApp-veins-offlinedocs.desktop', 'firefox-esr.desktop', 'org.gnome.Nautilus.desktop', 'terminator.desktop']"

- name: Copy background picture
  become_user: veins
  copy:
    src: "veins-background.jpg"
    dest: "/home/veins/Documents/veins-background.jpg"
    mode: 0644

- name: Background
  become_user: veins
  shell: |
    set -exu
    xvfb-run gsettings set org.gnome.desktop.background picture-uri 'file:///home/veins/Documents/veins-background.jpg'

- name: Disable Screensaver
  become_user: veins
  shell: |
    set -exu
    xvfb-run gsettings set org.gnome.desktop.session idle-delay 0
    xvfb-run gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type "nothing"

- name: Script for graphical login
  become_user: veins
  copy:
    content: |
      # Show help on first login
      if [ -f ".veins-first-login" ]; then
        echo "not the first login"
      else
        gnome-help &
        touch .veins-first-login

        echo "Please wait while OMNeT++ and SUMO are being built..."

        # Build OMNeT++
        cd /home/veins/src/omnetpp
        source setenv
        ./configure
        make -j${nproc}

        # Build SUMO
        cd /home/veins/src/sumo
        export SUMO_HOME="$PWD"
        mkdir build/cmake-build && cd build/cmake-build
        cmake ../..
        make -j${nproc}

        # Build AirMobiSim
        cd /home/veins/src/AirMobiSim
        ./build.sh

      fi
    dest: /home/veins/.gnomerc
    mode: 0755

- name: Script for gnome login
  become_user: veins
  copy:
    content: |
      # Load common environment variables and shell config
      . ~/.shrc
    dest: /home/veins/.profile
    mode: 0755

- name: Copy zshrc
  become_user: veins
  copy:
    src: ".zshrc"
    dest: "/home/veins/.zshrc"
    mode: 0755

- name: Script for zsh login
  become_user: veins
  copy:
    content: |
      # Load common environment variables and shell config
      . ~/.shrc
    dest: /home/veins/.zprofile
    mode: 0755

- name: Script for installing virtualbox-guest-tools
  become_user: veins
  copy:
    content: |
      #!/bin/bash
      set -e
      sudo sh -c "echo 'deb http://deb.debian.org/debian/ bullseye main non-free\ndeb http://security.debian.org/ bullseye-security main non-free\ndeb http://deb.debian.org/debian/ bullseye-updates main non-free\n' > /etc/apt/sources.list.d/debian-bullseye-nonfree.list"
      sudo apt update
      sudo apt install virtualbox-guest-additions-iso
      sudo mount /usr/share/virtualbox/VBoxGuestAdditions.iso /mnt
      sudo /mnt/VBoxLinuxAdditions.run || echo "Installation aborted. This is not necessarily a problem, so continuing anyway."
      sudo umount /mnt
      echo Please reboot machine to make sure changes are applied...
    dest: /home/veins/bin/virtualbox-guest-install.sh
    mode: 0755

- name: Build Workspace
  become_user: veins
  shell: |
    set -exu
    source /home/veins/.shrc
    xvfb-run /home/veins/src/omnetpp/ide/omnetpp --launcher.suppressErrors -data /home/veins/workspace.omnetpp -nosplash -application org.eclipse.cdt.managedbuilder.core.headlessbuild -build all || echo "build all: exit code $? is suppressed"
  args:
    executable: /bin/bash
    chdir: /home/veins/src

#- name: Remove OMNeT
#  become_user: veins
#  shell: |
#    set -exu
#    make clean
#  args:
#    executable: /bin/bash
#    chdir: /home/veins/src/omnetpp

#- name: Remove SUMO
#  become_user: veins
#  shell: |
#    set -exu
#    rm -rf /home/veins/src/sumo/bin
#    rm -rf /home/veins/src/sumo/build/
#  args:
#    executable: /bin/bash
#    chdir: /home/veins/src

#- name: Remove airmobisimVeins
#  become_user: veins
#  shell: |
#    set -exu
#    make clean
#  args:
#    executable: /bin/bash
#    chdir: /home/veins/src/airmobisimVeins

#- name: Patch preferences to show (sub)projects in navigator without nesting
#  become_user: veins
#  copy:
#    content: |
#      eclipse.preferences.version=1
#      #org.eclipse.ui.navigator.ProjectExplorer.activatedExtensions=org.eclipse.cdt.make.ui.makeTargets.content\=true;org.eclipse.ui.navigator.resourceContent\=true;org.eclipse.cdt.ui.navigator.content\=true;org.eclipse.egit.ui.changeSetContent\=false;org.eclipse.ui.navigator.resources.workingSets\=true;org.eclipse.team.ui.patchSyncNavigatorContent\=true;org.eclipse.team.ui.resourceContent\=true;org.eclipse.ui.navigator.resources.nested.nestedProjectContentProvider\=false;org.eclipse.egit.ui.RepositoriesViewContent\=true;org.omnetpp.navigator.content\=true;
#      #org.eclipse.ui.navigator.ProjectExplorer.filterActivation=\:org.eclipse.ui.navigator.resources.filters.startsWithDot\:org.eclipse.cdt.ui.navigator.filters.ForwardDeclarationFilter\:
#    dest: /home/veins/workspace.omnetpp/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.ui.navigator.prefs
#    mode: 0644

